//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/PuzzleSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/PuzzleSchema.xsd", IsNullable=false)]
public partial class puzzle {
    
    private string typeField;
    
    private string difficultyField;
    
    private int gridsizeField;

    //Changed to a list, for better handling. 
    private List<puzzleCell> puzzlecellsField = new List<puzzleCell>();

    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string difficulty {
        get {
            return this.difficultyField;
        }
        set {
            this.difficultyField = value;
        }
    }
    
    /// <remarks/>
    public int gridsize {
        get {
            return this.gridsizeField;
        }
        set {
            this.gridsizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("cell", IsNullable=false)]
    public List<puzzleCell> puzzlecells {
        get {
            return this.puzzlecellsField;
        }
        set {
            this.puzzlecellsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/PuzzleSchema.xsd")]
public partial class puzzleCell {
    
    private int blocknumberField;
    
    private int rownumberField;
    
    private int columnnumberField;
    
    private int valueField;
    
    private int solutionvalueField;
    
    /// <remarks/>
    public int blocknumber {
        get {
            return this.blocknumberField;
        }
        set {
            this.blocknumberField = value;
        }
    }
    
    /// <remarks/>
    public int rownumber {
        get {
            return this.rownumberField;
        }
        set {
            this.rownumberField = value;
        }
    }
    
    /// <remarks/>
    public int columnnumber {
        get {
            return this.columnnumberField;
        }
        set {
            this.columnnumberField = value;
        }
    }
    
    /// <remarks/>
    public int value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    public int solutionvalue {
        get {
            return this.solutionvalueField;
        }
        set {
            this.solutionvalueField = value;
        }
    }
}
