//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Statistics.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/Statistics.xsd", IsNullable=false)]
public partial class statistics {
    
    private decimal fastestsolvetimeField;
    
    private int puzzlecompletedField;
    
    private int numberOfExtremePuzzleCompletedField;
    
    private int levelcompletedField;
    
    private int hintNumberField;
    
    private int extremeHighScoreField;
    
    private int hardHighScoreField;
    
    private int mediumHighScoreField;
    
    private int easyHighScoreField;
    
    /// <remarks/>
    public decimal fastestsolvetime {
        get {
            return this.fastestsolvetimeField;
        }
        set {
            this.fastestsolvetimeField = value;
        }
    }
    
    /// <remarks/>
    public int puzzlecompleted {
        get {
            return this.puzzlecompletedField;
        }
        set {
            this.puzzlecompletedField = value;
        }
    }
    
    /// <remarks/>
    public int numberOfExtremePuzzleCompleted {
        get {
            return this.numberOfExtremePuzzleCompletedField;
        }
        set {
            this.numberOfExtremePuzzleCompletedField = value;
        }
    }
    
    /// <remarks/>
    public int levelcompleted {
        get {
            return this.levelcompletedField;
        }
        set {
            this.levelcompletedField = value;
        }
    }
    
    /// <remarks/>
    public int hintNumber {
        get {
            return this.hintNumberField;
        }
        set {
            this.hintNumberField = value;
        }
    }
    
    /// <remarks/>
    public int extremeHighScore {
        get {
            return this.extremeHighScoreField;
        }
        set {
            this.extremeHighScoreField = value;
        }
    }
    
    /// <remarks/>
    public int hardHighScore {
        get {
            return this.hardHighScoreField;
        }
        set {
            this.hardHighScoreField = value;
        }
    }
    
    /// <remarks/>
    public int mediumHighScore {
        get {
            return this.mediumHighScoreField;
        }
        set {
            this.mediumHighScoreField = value;
        }
    }
    
    /// <remarks/>
    public int easyHighScore {
        get {
            return this.easyHighScoreField;
        }
        set {
            this.easyHighScoreField = value;
        }
    }
}
