//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Statistics.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/Statistics.xsd", IsNullable=false)]
public partial class tip {
    
    private string tiptitleField;
    
    private string tipcontentField;
    
    private string tippicturedirectorylocationField;
    
    /// <remarks/>
    public string tiptitle {
        get {
            return this.tiptitleField;
        }
        set {
            this.tiptitleField = value;
        }
    }
    
    /// <remarks/>
    public string tipcontent {
        get {
            return this.tipcontentField;
        }
        set {
            this.tipcontentField = value;
        }
    }
    
    /// <remarks/>
    public string tippicturedirectorylocation {
        get {
            return this.tippicturedirectorylocationField;
        }
        set {
            this.tippicturedirectorylocationField = value;
        }
    }
}
